# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
      tailwindcss:
        patterns:
          - "@tailwindcss/vite"
          - "tailwindcss"
      tanstack-start:
        patterns:
          - "@tanstack/eslint-plugin-router"
          - "@tanstack/react-router*"
          - "@tanstack/react-start*"
          - "@tanstack/router*"
      turbo:
        patterns:
          - "turbo"
          - "eslint-plugin-turbo"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
