name: "Setup and install"
description: "Setup Node.js and install dependencies"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: "yarn"

    - shell: bash
      run: yarn
